### ISSUE TITLE
support windows build ?

### ISSUE THREAD

**Issue by WingDust** [Unisay/purescript-lua#13]

**Comment by CharlesTaylor7** [comment]
The `flake.nix` file only supports linux, but I suspected the project would build on other platforms using cabal directly.

Here's how I got this to build:
- Get GHCup (https://www.haskell.org/ghcup/)
- Use ghcup to install the recommended cabal version
- Use ghcup to install GHC 9.2.x
Clone the repo and run `cabal install` in the root directory. 
That will build and install `pslua` to `$HOME/.cabal/bin/pslua`. 


Those steps worked for me on an Arm Macbook, but they ought to work on Windows too since `ghcup`, `cabal`, and `ghc` are cross platform.

**Comment by Unisay** [comment]
I've added instructions how to build `pslua.exe` on Windows to the README.md
